### ISSUE TITLE
Converting SVG IDs to classes

### ISSUE THREAD

**Issue by smoses2** [iconic/grunt-svg-toolkit#3]
Great plugin.  I found this when I was trying to find a way to convert Illustrator output IDs to classes (to avoid duplicates with multiple SVGs).  I saw on https://github.com/iconic/illustrator-svg-exporter, that grunt-svg-toolkit does that. 

However, illustrator outputs the layer names to "g" group elements (at least in CS6, the version I have).
So when I run the toolkit in Grunt, it does not convert the IDs to classes on the group elements.  However, when I edited your code in "ids-to-classes.js", adding on "g" to the var shapesAndText, this worked fine.

Please consider adding "g" groups to the elements that will convert IDs to classes.

**Comment by protodave** [comment]
Thanks for the feedback! I'll take a look.

**Comment by smoses2** [comment]
Great - thanks.
